### ISSUE TITLE
Selection of multiple dates

### ISSUE THREAD

**Issue by PhilippKrone** [stephy/CalendarPicker#10]
Hi,

is there the intention to implement a feature that allows to basically select a from and end date? E.g. by swiping from one date to the other?

Would gladly support this implementation.

Regards
Philipp

**Comment by luisfuertes** [comment]
I need too select two or more days for events.

Can custom color too?

**Comment by luisfuertes** [comment]
Oh and there are a prop that run but dont have on Readme. selectedDayTextColor.

**Comment by abeikverdi** [comment]
Is there a support to select more than one day?

**Comment by ararog** [comment]
@abeikverdi I created [this](https://github.com/stephy/CalendarPicker/pull/44) PR, right now the only known limitation is the ability to select a range within a month, support to select a range across more than one month isn't available.

**Comment by stephy** [comment]
Hi Everyone, This has been added to version 4 and 5 of the calendar. v5 is a complete rewrite of the calendar. See Readme for more information.

**Comment by Hamza-Ali333** [comment]
i saw readme but still unable to find the multiple date select props.
