### ISSUE TITLE
Wrong format when starting on mondays

### ISSUE THREAD

**Issue by kvasbo** [stephy/CalendarPicker#100]
When setting "startFromMonday", the day names shift, but the dates do not. However, the objects returned when selecting a date are of course correct. 

<img width="355" alt="skjermbilde 2018-02-20 kl 12 59 13" src="https://user-images.githubusercontent.com/359896/36422802-e0b99bd2-163d-11e8-9221-941129c5dfdb.png">

**Comment by peacechen** [comment]
Good catch.  I don't have time to fix it, and not sure who else may.  If you're up for making a PR, I'll merge and release ASAP.

**Comment by peacechen** [comment]
Published 5.14.0
