### ISSUE TITLE
Customizing previous and next titles

### ISSUE THREAD

**Issue by HugoChengMyC** [stephy/CalendarPicker#108]
Is there currently any method to apply style specifically to the "previous" and "next " titles?

**Comment by peacechen** [comment]
Not currently.  PRs are welcome :)

**Comment by peacechen** [comment]
This feature was added in 6.0.4 with props `previousTitleStyle` and `nextTitleStyle`.
https://github.com/stephy/CalendarPicker#calendarpicker-props

Additionally, props `previousComponent` and `nextComponent` allow for replacing them entirely with components of your choice.
