### ISSUE TITLE
onDateChange is not a function

### ISSUE THREAD

**Issue by micodel** [stephy/CalendarPicker#110]
The README lists all props as optional, so I rendered ```<CalendarPicker />``` as a test.

When clicking on a calendar date it throws an error: "onDateChange is not a function"

If this field is required, please update the README.
If this field should be optional, the issue may be with the defaultProp.

**Comment by peacechen** [comment]
Thanks for noticing this.  An easy fix would be to add a default prop with an empty function.

**Comment by peacechen** [comment]
Fixed in PR #111.

**Comment by micodel** [comment]
Thanks for such fast action on this!
