### ISSUE TITLE
max date is not working fine

### ISSUE THREAD

**Issue by prashantm8** [stephy/CalendarPicker#124]
passing 
            maxDate={new Date(today.add(1,'years'))}
is not working all the date are disabled. While on passing 
             maxDate={new Date (2019,6,6)}
works fine. Since I need to pass max date as 1 year from today. I calculated today using moment 
            let today = moment(new Date());

**Comment by peacechen** [comment]
You're passing a Moment object to a JS Date which doesn't work, as you found. 
```
maxDate={new Date(today.add(1,'years'))}
```

If you want to make a copy of the date (so the .add doesn't mutate the original object), use the clone() method.
```
maxDate={today.clone().add(1,'years')}
```
