### ISSUE TITLE
Changing Months options

### ISSUE THREAD

**Issue by PvanHengel** [stephy/CalendarPicker#125]
For us, the swipe event is very slow to fire and change, this seems like an issue to me, its unusable.  Not sure if others have this.  Aside that from being an issue, it would be nice to enable a 'scroll' mode so users could scroll up and down, sort of like how the calendar month view looks on the iphone.

**Comment by YevhenLobanov** [comment]
@PvanHengel it is more like improvement, but nice to have, also as time in utc

**Comment by peacechen** [comment]
It sounds like you would like to show multiple months in a scroll view.  That would be a handy feature.  Would you mind submitting a PR?

**Comment by AdrianBordeianu** [comment]
Was this implemented?

**Comment by peacechen** [comment]
The scrollable feature was added in 7.0.0.  Use props `scrollable` and `horizontal`.
