### ISSUE TITLE
How to style selected range

### ISSUE THREAD

**Issue by aiynmm** [stephy/CalendarPicker#126]
I want to know how do you write the style to render when selecting range, I can't find that where are the default `selectedRangeStartStyle`, `selectedRangeEndStyle ` and `selectedRangeStyle` initing in your code?

**Comment by peacechen** [comment]
It uses standard React style syntax.
```
<CalendarPicker
  selectedRangeStartStyle={{backgroundColor: 'yellow'}}
  etc...
/>
```
