### ISSUE TITLE
Can we change in theme ?

### ISSUE THREAD

**Issue by avs30390** [stephy/CalendarPicker#129]
Hi,

Please let me know , Is there any option to change in theme ?
Please find the attached screenshot as reference  .

![screen shot 2018-08-02 at 6 22 25 pm](https://user-images.githubusercontent.com/11497020/43584997-97d5a874-9681-11e8-81de-82177fe3ab55.png)

**Comment by peacechen** [comment]
Many props are available to style the calendar.  I encourage you to review the documentation:
https://github.com/stephy/CalendarPicker#calendarpicker-props

What specifically are you trying to style?

**Comment by avs30390** [comment]
I have already attached the screenshot please have a look.I am looking for same as screenshot.

**Comment by avs30390** [comment]
when we click on arrow , next date will be shown.

**Comment by peacechen** [comment]
Are you posting in the correct repo?  That looks like [react-native-calendar-strip](https://github.com/BugiDev/react-native-calendar-strip)

**Comment by peacechen** [comment]
This calendar component shows a month at a time.  PRs are welcome if you would like to contribute new features.
