### ISSUE TITLE
Custom date

### ISSUE THREAD

**Issue by mozamonkey** [stephy/CalendarPicker#131]
How can we make the onDateChange value only show the date and not the time zone?

**Comment by peacechen** [comment]
It's up to you (the app developer) to format the datetime the way you like.  The callback returns a Moment JS object, so you could use this to print the date:
```
date.format('MM-DD-YYYY');
```

**Comment by mozamonkey** [comment]
Is it possible to add a format that forms a sentence? Like "Monday August 20"?

I know that's done by default but if I want to convert from MM/DD/YYYY to the above format is that possible through Moment js?

**Comment by peacechen** [comment]
Moment JS has an extensive set of format options:
https://momentjs.com/docs/#/displaying/
