### ISSUE TITLE
 Module `moment` does not exist in the Haste module map

### ISSUE THREAD

**Issue by wolfjobs** [stephy/CalendarPicker#134]
`Error: Unable to resolve module `moment` from `${rootProject}/node_modules/react-native-calendar-picker/CalendarPicker/index.js`: Module `moment` does not exist in the Haste module map`

`"react": "^16.5.0",
   "react-native": "^0.57.0",
   "react-native-calendar-picker": "^5.22.0",
`

**Comment by peacechen** [comment]
Moment is a peer dependency, which means you need to place it in your app's package.json.  It should have printed a warning that the peer dependency was not met when you ran `npm install`.
