### ISSUE TITLE
Prop incorrectly named?

### ISSUE THREAD

**Issue by rolfb** [stephy/CalendarPicker#142]
https://github.com/stephy/CalendarPicker/blob/ab5bff9f9761c2f8b40e173737acec63a1123963/CalendarPicker/index.js#L289

**Comment by peacechen** [comment]
That style comes from the call to `makeStyles`, which returns the `calendar` style:
https://github.com/stephy/CalendarPicker/blob/ab5bff9f9761c2f8b40e173737acec63a1123963/CalendarPicker/makeStyles.js#L16

**Comment by rolfb** [comment]
syles should still be named styles though?

**Comment by peacechen** [comment]
Good catch!  Thanks for noticing this.  Would you mind creating a PR?

**Comment by rolfb** [comment]
That wasn't quite as straight-forward as expected. Seems like styles object is undefined in the tests? Run tests for this branch to see.

**Comment by rolfb** [comment]
Seems like there are more places where `style` and `styles` are swapped around such as HeaderControls expecting `styles` prop but when initiated it gets `style` prop.

**Comment by rolfb** [comment]
All better now ;-)

**Comment by peacechen** [comment]
Thanks @rolfb for the comprehensive PR
