### ISSUE TITLE
enableDateChange not working

### ISSUE THREAD

**Issue by cadeabrahams** [stephy/CalendarPicker#145]
**Example**
>  <CalendarPicker
>                                         ref={this.setCalendarRef}
>                                         startFromMonday={true}
>                                         allowRangeSelection={true}
>                                         minDate={minDate}
>                                         maxDate={maxDate}
>                                         todayTextStyle={{fontWeight: 'bold'}}
>                                         todayBackgroundColor={'transparent'}
>                                         selectedDayColor={Theme.palette.primary}
>                                         selectedDayTextColor="#FFFFFF"
>                                         width={deviceWidth-75}
>                                         selectedStartDate={selectedStartDate}
>                                         selectedEndDate={selectedEndDate}
>                                         initialDate={selectedStartDate}
>                                         enableDateChange={false}
>    />

**Expected Behaviour**
enableDateChange={false} should block updating dates, which it does not do graphically.

**Comment by peacechen** [comment]
Thanks for reporting this.  It looks like the touch handler isn't looking at the `enableDateChange` prop.
https://github.com/stephy/CalendarPicker/blob/master/CalendarPicker/Day.js#L161

That prop will need to be passed down from parent to child 2 layers deep.  Would you like to create a PR?
