### ISSUE TITLE
resetSelections internal function not accessible?

### ISSUE THREAD

**Issue by bmcn99** [stephy/CalendarPicker#147]
EDIT: NEVERMIND. I'm not sure what I was doing wrong previously but after noticing I was on an older version and upgrading to 6.0.0 I saw it worked just fine without that this.resetSelections = this.resetSelections.bind(this) line. Curious, I went back to the version I was using previously and it worked fine there too. So this is definitely a non-bug, sorry.

I get my reference to CalendarPicker with ref={ (ref) => this.myRef = ref }.

After doing this and consoling out myRef I found that I still didn't have access to resetSelections, and so had to modify the index.js to include this at the top: this.resetSelections = this.resetSelections.bind(this);, same as the other internal function handleOnPressDay, handleOnPressNext, and handleOnPressPrevious.

I'm flying by the seat of my pants here with RN in general so I have to ask if there's a proper way to access that function already in place or if this is a bug fix?

**Comment by peacechen** [comment]
Hard to say what happened.  My first guess is that hot-reloading was involved.  That can munge things up during debug.

It would be best to bind `resetSelections()` to CalendarPicker's context.  I'll make that fix right now.  Let me know if this is a real bug and I'll publish it.

**Comment by 1ba1** [comment]
Hi, I'm trying to access `resetSelections()` via `useRef` hook, but `myCalendarPicker` is always `null`
Is this a bug or am I doing something wrong? Thanks in advance

```
const myCalendarPicker = useRef(null)

return (
  <CalendarPicker
    ref={myCalendarPicker}
  />
)
```

**Comment by peacechen** [comment]
Haven't tried the useRef hook with this component.  Does this work?
```
let myRef;

return (
  <CalendarPicker
    ref={ (ref) => this.myRef = ref }.
  />
)
```

**Comment by jjg77** [comment]
You can do this:

```
const refCal = React.useRef();

<CalendarPicker
   ref={refCal}
```

Then call it like this:

`onPress={() => refCal.current.resetSelections()}`

**Comment by kameshdhana** [comment]
Still it's not working, Did you guys found an fix?

**Comment by Natacuin** [comment]
> Haven't tried the useRef hook with this component. Does this work?
> 
> ```
> let myRef;
> 
> return (
>   <CalendarPicker
>     ref={ (ref) => this.myRef = ref }.
>   />
> )
> ```

That worked for me.
