### ISSUE TITLE
Controller for monthLabel

### ISSUE THREAD

**Issue by AdrianBordeianu** [stephy/CalendarPicker#148]
Is there any solution for adding an action such as onPressMonthLabel? Because swiping is super slow, and an user might want to go to a date 2-3 years in the past/future I would like to have a months popup or something in order to scroll through months.

**Comment by peacechen** [comment]
Adding `onMonthPress` should be relatively straight-forward.  PRs are welcome 😄

**Comment by scy0846** [comment]
I just created a PR for this and for a year press as well. I just need to figure out the test snapshot as I made some large changes and it no longer matches the snapshot on the test. The snapshot test is a bit new to me, but if you need this feature now feel free to branch off my branch. If you can help adjust the tests or anything feel free to help me there as well. Check out PR #151

**Comment by peacechen** [comment]
This has been implemented in commit 67a03746500896ab2a8c90421fde71fa5f00d34b .
