### ISSUE TITLE
Next and previous dates of months

### ISSUE THREAD

**Issue by gHashTag** [stephy/CalendarPicker#152]
How to add the following and send the dates of the months?
<img width="340" alt="Screenshot 2019-04-20 at 16 34 24" src="https://user-images.githubusercontent.com/6774813/56454901-7b7df600-638a-11e9-9b34-95bcd8fdcc98.png">

**Comment by peacechen** [comment]
That feature isn't currently available.  You're welcome to submit a PR.  I'll merge it promptly.

**Comment by peacechen** [comment]
This feature has been added in commit 7b09d30aea9a040c14bb284a727f7eb8ff503004 and exposed via the `showDayStragglers` prop.

Try it out by pointing directly to this repo in your package.json.
```
dependencies: {
    "react-native-calendar-picker": "https://github.com/stephy/CalendarPicker",
}
```
