### ISSUE TITLE
When 1st day of Month is Sunday, the first row is blank

### ISSUE THREAD

**Issue by razirbel** [stephy/CalendarPicker#153]
When 1st day of Month is Sunday, the first row is blank.  If you have 'startFromMonday' = false or omit the option, when you toggle through the months, if the first day of the month falls on a Sunday, the entire first row is blank.

**Comment by peacechen** [comment]
Thanks for the bug report.  Please post a code snippet with the props that recreate the issue (startDate, startFromMonday, etc).

**Comment by razirbel** [comment]
render() {
        return (
            <Modal isVisible={true}  style={{ margin: 0 }} backdropOpacity={0.5}>
              <View style={{ flex: 1, marginTop: 100 }}>      
                  <CalendarPicker
                    startFromMonday={false}
                    allowRangeSelection={true}
                    onDateChange={this.onDateChange}                
                  />  
              </View>    
            </Modal>
        );
    }

**Comment by peacechen** [comment]
Please paste text instead of a bitmap next time.  Can't copy the code easily from a bitmap.

July 2018 shows the case you described.  The entire month is still displayed, but the top row has extra space.
https://snack.expo.io/HywKRqW6E

**Comment by razirbel** [comment]
I am sorry about that.  I tried to paste the text but for some reason the <CalendarPIcker text and everything following didn’t show up except in the preview, I am not sure why.

**Comment by razirbel** [comment]
Thank You!

**Comment by peacechen** [comment]
Fix released in 6.0.1.  Thanks @RohanTalip
