### ISSUE TITLE
Add Icons to and text to change month 

### ISSUE THREAD

**Issue by guilhermepatriarca** [stephy/CalendarPicker#163]
The user can choose if want icon our text or both

**Comment by peacechen** [comment]
That would be a nice feature.  Would you mind submitting a PR?

**Comment by guilhermepatriarca** [comment]
I try give me 1 day

A domingo, 15/09/2019, 03:56, Peace <notifications@github.com> escreveu:

**Comment by guilhermepatriarca** [comment]
i try run in develop mode because the sdk(15.0.0) is to old.

**Comment by vforvasile** [comment]
Here: [https://github.com/stephy/CalendarPicker/pull/169](https://github.com/stephy/CalendarPicker/pull/169)

**Comment by peacechen** [comment]
This has been implemented in commit 859f3423d9b5f46dac95ef4fc36f5e2eb7ff3383.
