### ISSUE TITLE
Select range issue

### ISSUE THREAD

**Issue by akhlopyk** [stephy/CalendarPicker#166]
Hi there!

I have got an issue with range selection.
I have used selectedStartDate and selectedEndDate (also allowRangeSelection: true). Refreshing the app and got only one date selected. If I click on another date (assume it gonna be END_DATE) the selection jumps out to previews date.

Any suggestions?
I would appreciate it.

Thanks

**Comment by peacechen** [comment]
Please post a code snippet with your usage of `<CalendarPicker>`.

You can debug this by setting breakpoints on the node_modules/react-native-calendar-picker/CalendarPicker/*.js files.  PR's are welcome.

**Comment by akhlopyk** [comment]
Oh! That was my fault. No issue with this! Closing it!
