### ISSUE TITLE
API for changing displayed month

### ISSUE THREAD

**Issue by lironsher** [stephy/CalendarPicker#172]
I'm looking for API I can change the displayed month.

For example, if currently displayed Jan, I want to change from an outside button to October.

**Comment by peacechen** [comment]
Try changing the `initialDate` prop.  Set it to any day of the month that you'd like the calendar to change to.

**Comment by peacechen** [comment]
Alternatively, you could use the `handleOnPressDay` method from the CalendarPicker's ref:
https://github.com/stephy/CalendarPicker#methods
