### ISSUE TITLE
Calendar height not increasing.

### ISSUE THREAD

**Issue by IbrahimSheikh24** [stephy/CalendarPicker#173]
Calendar height is equal to the width of calendar. If I am giving static value to height then also no changes are reflecting, but If I am increasing width of calendar then height also increasing, i.e height is dependent on width. 
scaleFactor prop also making height dependent on width.
My question is to only increase the height of calendar and width should be device width.

**Comment by peacechen** [comment]
The height of the calendar varies depending on whether the month spans 4 or 5 week rows.  If CalendarPicker were to support a fixed height, then some months the calendar would look smaller.

Knowing that, if that behavior is what you prefer, please submit a PR and I'll review it right away.

**Comment by IbrahimSheikh24** [comment]
@peacechen my only concern is to increase the calendar height which is suppose to be 60% or 70% of device height. I am attaching two screenshot. First one is my expected calendar height and second screenshot is react-native-calendar-picker calendar whose height is equal to width.

![Screenshot_20200217_173444_com Clairvoyant FernsAndPetals](https://user-images.githubusercontent.com/57092389/74652599-63465580-51ac-11ea-98ff-4618b54c473f.jpg)

![Screenshot_20200217-173638](https://user-images.githubusercontent.com/57092389/74653432-1e232300-51ae-11ea-9cb6-a4d412598cbb.jpg)

**Comment by peacechen** [comment]
@IbrahimSheikh24 
In the 2nd screenshot, the disabled dates fonts are smaller.  `textStyle` adjusts the font size of the enabled dates, and `disabledDatesTextStyle` adjusts the font size of disabled dates.  However, that won't increase their height.  Try the `scaleFactor` prop.  Lowering it from the default 375 should create bigger days.
https://github.com/stephy/CalendarPicker#calendarpicker-props

If that doesn't increase the height to suit your needs, a new prop will need to be added to style the day container.
