### ISSUE TITLE
Update to react-native 0.25

### ISSUE THREAD

**Issue by johnjerrico** [stephy/CalendarPicker#18]
Deprecations

Requiring React API from react-native is now deprecated - 2eafcd4 0b534d1

Instead of:

import React, { Component, View } from 'react-native';
you should now:

import React, { Component } from 'react';
import { View } from 'react-native';

#see the following link https://github.com/facebook/react-native/releases/tag/v0.25.1

**Comment by johnjerrico** [comment]
Hi,
@sibeliusseraphini provides tools to update to 0.25
https://github.com/sibeliusseraphini/codemod-RN24-to-RN25

**Comment by stephy** [comment]
This issue has been resolved.
