### ISSUE TITLE
restrictMonthNavigation props hiding next and previous button but not controlling the swipe event if previous and next dates are not available.

### ISSUE THREAD

**Issue by IbrahimSheikh24** [stephy/CalendarPicker#182]
restrictMonthNavigation props working as expected which hides previous and next button if dates are less than startDate and greater than endDate, but if I swipe the calender then its showing previous month calendar whose dates are less than startDate. How to handle this issue, please guide me.

**Comment by peacechen** [comment]
Thanks for noting this bug.  It sounds like the swiping code isn't respecting the `restrictMonthNavigation`.  If you have time, please submit a PR to fix this.

**Comment by peacechen** [comment]
The scrollable feature was added in 7.0.0 and also fixes this issue.  Use props `scrollable` and `horizontal`.
