### ISSUE TITLE
dayOfWeekStyles and customDatesStyles cannot be used at the same time

### ISSUE THREAD

**Issue by ipa127001** [stephy/CalendarPicker#185]
I want to highlight Sundays and public holidays in red.

I use dayOfWeekStyles to highlight all Sundays in red and use customDatesStyles to highlight all public holidays.  If either one is used, the days are highlighted as expected.  However, if both dayOfWeekStyles and customDatesStyles are assigned in props, dayOfWeekStyles will be overridden by customDatesStyles even the days are not overlapped.

I think the issue is caused by the following lines:
https://github.com/stephy/CalendarPicker/blob/794cde077d0a8ec51cb07e69cf6c48b2f524e5eb/CalendarPicker/index.js#L324-L329

Is there any solution?

**Comment by peacechen** [comment]
Thanks for noting this issue.  That looks like the culprit.  `dayOfWeekStyles` is a relatively new feature and there wasn't a clear reason to have it override `customDatesStyles`.  We could add a new global prop to choose which overrides the other, but it would be more flexible to add a flag in `customDatesStyles` to indicate which one to use.  My proposal would be to add the boolean flag `dayOfWeekStylesPrecedence` which would allow individual control of whether a customDatesStyle overrides a dayOfWeekStyle.

This would require refactoring the logic that processes those props.  Would you like to submit a PR?

**Comment by peacechen** [comment]
The `customDatesStylesPriority` prop has been added in #194.

**Comment by peacechen** [comment]
Published in 6.1.0

**Comment by peacechen** [comment]
@ipa127001 

Callback support has been added to `customDatesStyles` in 6.1.5 which gives your app programmatic control over how any date is styled.  Code example:
https://github.com/stephy/CalendarPicker#styling-each-day-of-the-week-and-the-day-name-header

The callback can style a particular date, each day of the week, or a combination with priority determined by the callback.

`dayOfWeekStyles` and `customDatesStylesPriority` are deprecated and will be removed in the next version.
