### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by automatensalat** [stephy/CalendarPicker#188]
Hi there, 

I'm currently writing a Typescript declaration file for this package. 
Would you like the types to be included in this repository or do you want me to push them to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

Cheers!

**Comment by peacechen** [comment]
DefinitelyTyped looks to be a handy repo for TypeScript users. 

I'd be happy to merge your TS definition file.  Whether you place them here or on DefinitelyTyped is up to you.  If you are willing to maintain the definitions, we could ask for you to be added as a maintainer for this repo.

**Comment by automatensalat** [comment]
Alright, I'll see if I can get a PR ready today. I think I will monitor this repo and provide PRs if the API changes, however I'm not sure if I can commit to anything on the long term.

**Comment by automatensalat** [comment]
The types are available here: 
https://www.npmjs.com/package/@types/react-native-calendar-picker

**Comment by peacechen** [comment]
Thanks @automatensalat .  I'll add that to the Readme

**Comment by adilusman51** [comment]
@automatensalat  @peacechen 
According to source code of react-native-calendar-picker package, onDateChange callback has optional parameter type of values START_DATE | END_DATE

https://github.com/stephy/CalendarPicker/blob/c9087ee33c487eb81b17d3c6da6188f3a9d82742/CalendarPicker/index.js#L182

I have created a PR on `DefinitelyTyped` repo

**Comment by adilusman51** [comment]
[https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44378](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44378)

**Comment by automatensalat** [comment]
Thanks, I must have overlooked that :wave: 
We should add this to the docs of this package here as well then.

**Comment by peacechen** [comment]
Thanks @adilusman51 
I'll update the Readme to include that.

**Comment by adilusman51** [comment]
@peacechen @automatensalat Happy to help ... thanks for your cooperation

**Comment by peacechen** [comment]
FYI new props have been added and will be in the 6.1.0 release.  Currently squashing some bugs.
`allowBackwardRangeSelect`, `previousComponent`, `nextComponent`, `customDatesStylesPriority`.
https://github.com/stephy/CalendarPicker#calendarpicker-props

**Comment by automatensalat** [comment]
Thanks for the notice, I'll update the types by weekend unless somebody beats me to it

**Comment by automatensalat** [comment]
I created a PR to include the documented new props for releases 6.1.0 and 6.1.1.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44593

**Comment by adilusman51** [comment]
@automatensalat Kindly incooperate this PR as well 
[fix: optional parameter `type` missing in DateChangedCallback #44378](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44378)

**Comment by automatensalat** [comment]
@adilusman51 Not sure what's more to do from my side, I did approve of the changes 11 days ago. I think it's still waiting for a DefinitelyTyped maintainer to review the changes.

**Comment by automatensalat** [comment]
Sorry to dig this issue up again. 

@peacechen I noticed you released a new version introducing new props. I'm about to sync the TS types. While inspecting the code I noticed that although the doc for `customDayHeaderStyles` mentions that the func is supposed to return both a `style` and a `textStyle`, only the `textStyle` seems to be used:
```js
// Weekdays.js
if (customDayHeaderStyles instanceof Function) {
          const dayOfWeek = dayOfWeekNums[key];
          customDayOfWeekStyles = customDayHeaderStyles({dayOfWeek, month, year}) || {};
          dayOfWeekTextStyle.push(customDayOfWeekStyles.textStyle);
        }
```
Does this mean that the implementation is incomplete or that the `style` is indeed not needed? If the latter is the case then I'll omit this from the type defs.

**Comment by peacechen** [comment]
The `styles` key is used towards the end of that section:
https://github.com/stephy/CalendarPicker/blob/master/CalendarPicker/Weekdays.js#L57

**Comment by automatensalat** [comment]
Ah you're right, I missed that somehow. I'll create a PR later today :+1:

**Comment by peacechen** [comment]
That's an easy one to miss.

Note that `dayOfWeekStyles` and `customDatesStylesPriority` have been deprecated.  They continue to function in this version  but will be removed in the next release.  Is there a good way to mark deprecated props in TS?

**Comment by automatensalat** [comment]
Yes, I'll mark the props as `@deprecated` in the jsdoc, along with a description of what to use instead.
