### ISSUE TITLE
Add support for custom components on previousTitle and nextTitle

### ISSUE THREAD

**Issue by rochagbr** [stephy/CalendarPicker#193]
We have some PR in progress to add this functionality? If not, i'm free for do this?
Thanks.

**Comment by rochagbr** [comment]
I've did see this issue #169 , but is not complete cuz the merge conflict.
Waiting for your answer  :)

**Comment by peacechen** [comment]
Yes please submit a PR.  That other one is outdated and the author has vanished.

**Comment by peacechen** [comment]
@rochagbr 
I wanted to check whether you're working on this.  I am starting to refactor that PR and streamline the props.

**Comment by rochagbr** [comment]
@peacechen 
hello, I still haven't been able to dedicate time for this, so you can proceed without problems. sorry for being late.

**Comment by peacechen** [comment]
This feature has been added in commit 859f3423d9b5f46dac95ef4fc36f5e2eb7ff3383.

Refer to the documentation for props `previousComponent` and `nextComponent`.
https://github.com/stephy/CalendarPicker#calendarpicker-props

**Comment by peacechen** [comment]
Published in 6.1.0
