### ISSUE TITLE
External images in source code

### ISSUE THREAD

**Issue by edvinerikson** [stephy/CalendarPicker#2]
Is there any specific reason you are having the images separated from the repo?
The current solution isn't the best because it's creating an huge dependency to the website that hosts those images.

I would suggest that we change 
```javascript
source={{ uri: 'http://stephanimoroni.com/kalendar/images/arrow-left@3x.png'}}/>
```
[(source)](https://github.com/stephy/CalendarPicker/blob/master/CalendarPicker.js#L200) to 
```javascript
source={{ uri: 'images/arrow-left@3x.png'}}/>
```
and the same with the right arrow. [(source)](https://github.com/stephy/CalendarPicker/blob/master/CalendarPicker.js#L210)

**Comment by stephy** [comment]
@edvinerikson, @brentvatne  Thank you for pointing that out. I used the url because I couldn't make the images load locally. I read up online and I finally figured it out. 

Here's the commit with the change: https://github.com/stephy/CalendarPicker/commit/e573b145ce37ba02d8d948453363df542308f0ab

**Comment by brentvatne** [comment]
:+1: :smile:

**Comment by edvinerikson** [comment]
Awesome! :smile:
I will close this now.
