### ISSUE TITLE
How can i custom Year title

### ISSUE THREAD

**Issue by NguyenDinhTrong99** [stephy/CalendarPicker#203]
Hi bro,
 The default header year title is "MM yyyy" but i want custom it
 i use mutilpe langue so i want custom calendar follow language
 ex: + japanese: '2020年 05五'
       + USA: '2020 05'
i hope u help me,
thanks u!

**Comment by peacechen** [comment]
Try the `months` prop and give it an array like `['01五', '02五', '03五', '04五', '05五', ...]`.
https://github.com/stephy/CalendarPicker#complex-example-changing-fonts-and-colors-language-and-etc

The month and year order can be reverse with the prop `monthYearHeaderWrapperStyle={{flexDirection: 'row-reverse'}}`
https://github.com/stephy/CalendarPicker#calendarpicker-props

At this time there is no prop to add a suffix to the year.  Please submit a PR to add that feature. This is a community supported library and contributions help yourself and others.

**Comment by NguyenDinhTrong99** [comment]
> Try the `months` prop and give it an array like `['01五', '02五', '03五', '04五', '05五', ...]`.
> https://github.com/stephy/CalendarPicker#complex-example-changing-fonts-and-colors-language-and-etc
> 
> The month and year order can be reverse with the prop `monthYearHeaderWrapperStyle={{flexDirection: 'row-reverse'}}`
> https://github.com/stephy/CalendarPicker#calendarpicker-props
> 
> At this time there is no prop to add a suffix to the year. Please submit a PR to add that feature. This is a community supported library and contributions help yourself and others.

It help me, thanks so much bro! 
Have a good day ^^

**Comment by aravi365** [comment]
@peacechen  I want the date to be displayed as `MONTH, YEAR` instead of `MONTH YEAR` . Anyway to do so?
