### ISSUE TITLE
android and iOS build crashing

### ISSUE THREAD

**Issue by mathritter** [stephy/CalendarPicker#205]
I’m usina Expo, just To begin with. In my Expo builds, it works fine, but when I release to TestFlight when the calendar mounts the app simply crashes. Any clue?

**Comment by mathritter** [comment]
I gotta say, it's actually crashing in both android and IOS, my bad.
Yes. it's using Moment JS localization

**Comment by mathritter** [comment]
I got a crash report from android, yeah, I now can see in the stack trace, it seems to be a problem with locale/pt-BR I added. Any advices on that?

**Comment by mathritter** [comment]
My code is like this:
```

import 'moment/locale/pt-br';
...etc
constructor(props) {
    super(props)
    this.state = {
      modalVisible: false,
      eventData: null,
      schedule: null,
      calendarMarked: null,
      modalContent: {}
    }
    moment().locale('pt-BR');
    this.onDateChange = this.onDateChange.bind(this);
  }
```

**Comment by peacechen** [comment]
The locale case should match the import.  This line looks suspicious:
```
moment().locale('pt-BR');
```

**Comment by mathritter** [comment]
Thank you very much turns out both had to be "pt-br". It worked, thank you for the quick response
