### ISSUE TITLE
When you set minDate -> today, and maxDate -> (today+ 1 year) and then try to select month manually, it just appears the current month.

### ISSUE THREAD

**Issue by JordaoMemoria** [stephy/CalendarPicker#207]

**Comment by peacechen** [comment]
@JordaoMemoria  Please include a code snippet or a [Snack](https://snack.expo.io/) that reproduces the issue.
It would also help if you placed the information in the comment body instead of just the title.

**Comment by peacechen** [comment]
7.0.0 fixed some bugs with month selection.  Please try that version; if the bug remains, feel free to re-open this.
