### ISSUE TITLE
How to add badge for each day in Months?

### ISSUE THREAD

**Issue by vhquan98** [stephy/CalendarPicker#209]
<img width="331" alt="Ảnh chụp Màn hình 2020-06-25 lúc 10 11 39" src="https://user-images.githubusercontent.com/44488592/85649015-45de4680-b6cc-11ea-866c-52a9ae6bf598.png">
i want to add badge for day in month!

**Comment by peacechen** [comment]
Days may be styled with the `customDatesStyles` prop:
https://github.com/stephy/CalendarPicker#custom-styling-individual-dates

`dayOfWeekStyles` is another option to style weekdays repeatedly.

Is that the type of badge that you're referring to?

**Comment by peacechen** [comment]
Callback support has been added to `customDatesStyles` in 6.1.5 which gives your app programmatic control over how any date is styled.  Code example:
https://github.com/stephy/CalendarPicker#styling-each-day-of-the-week-and-the-day-name-header

`customDayHeaderStyles` is another new prop that allows styling of the day name header.
