### ISSUE TITLE
npm ci fails 

### ISSUE THREAD

**Issue by richardszanyi** [stephy/CalendarPicker#211]
![image](https://user-images.githubusercontent.com/9089337/85925511-1fb9d180-b899-11ea-8362-2d9bdb0e9aa3.png)

npm ci fails after updating dependancy to 6.1.3, or 6.1.4. 
With 6.1.2 it works perfectly. Is it anything you are looking at?

Thanks!

**Comment by peacechen** [comment]
It's trying to run the node-git-hooks command during postinstall.  What OS and shell is that running on?  `./` refers to the current directory and I've tested it on Windows and OSX.  Very curious that it can't process the `./`.

**Comment by richardszanyi** [comment]
For me, its failing in local machine as well. Windows 10 pro 1909

**Comment by peacechen** [comment]
I tested again on a Windows 10 box and the postinstall script runs as expected.  Created a new project with `create-react-native-app` and added this dependency using:
> npm install --save react-native-calendar-picker

Are you using the standard Command Prompt or another shell?

**Comment by richardszanyi** [comment]
> node v12.16.2
> npm 6.14.4
> git version 2.26.2.windows.1

I have no idea what environment Gitlab's VM runs at.

**Comment by peacechen** [comment]
I upgraded to node v12.18.1 and npm 6.14.5.  Ran it in Git Bash and it still works.

Would you link to the specific Gitlab VM you're testing on?

**Comment by richardszanyi** [comment]
I'm not sure I can check gitlab's VM's specifications unfortunately :(

**Comment by peacechen** [comment]
6.1.5 should fix this 🤞

**Comment by richardszanyi** [comment]
It is fixed, closing issue! Thanks again
