### ISSUE TITLE
I want to remove the days container box and month,previous,next container box

### ISSUE THREAD

**Issue by jawwad22** [stephy/CalendarPicker#213]
hi, i am able to hide the days container and monther container by putting the style of display:"none" but there still a height, i want to removed that height too,
Thank you

**Comment by peacechen** [comment]
Are you trying to hide everything?  Without the days and month header, the only thing left would be the days of week title.

**Comment by yousefhossein** [comment]
I sove my problem thank you very much

در تاریخ سه‌شنبه ۳۰ ژوئن ۲۰۲۰،‏ ۱۱:۴۵ Peace <notifications@github.com> نوشت:
