### ISSUE TITLE
how to stop the swipe to future month

### ISSUE THREAD

**Issue by jawwad22** [stephy/CalendarPicker#214]
Hi again, if my current month is june, then i dont want to swipe to july or forward month, help me how can i acheive this??

**Comment by peacechen** [comment]
Fork this library, add the features you need, and submit a PR.  This is an open source library and community contributions are welcome.

**Comment by peacechen** [comment]
The scrollable feature was added in 7.0.0 and also fixes this issue.  Use props `scrollable` and `horizontal` to activate the scroller.

To prevent navigating to months outside of a range, use the props `minDate`, `maxDate`, and `restrictMonthNavigation`.
