### ISSUE TITLE
initialDate not working

### ISSUE THREAD

**Issue by maniac-tech** [stephy/CalendarPicker#215]
The initialDate prop of the CalendarComponent isn't populating the initial date being passed.

My Code snippet:
`<CalendarComponent initialDate={new Date(2020, 6, 13)} dateChanged={this.dateChanged}/>`

**Comment by peacechen** [comment]
`initialDate` sets the month that the calendar opens to.  `selectedStartDate` is the prop that marks a date as selected.

The prop `dateChanged` in your code snippet isn't supported.  You may have meant to use `onDateChange`.

**Comment by maniac-tech** [comment]
>  `selectedStartDate`

My intention here is to load the Calendar component with a provided date.

As per what you pointed, is this the right approach: 
`<CalendarComponent selectedStartDate={initalDate} onDateChange={this.dateChanged}/>` ?

**Comment by maniac-tech** [comment]
@peacechen The issue hasn't been resolved yet, your suggested way isn't working as expected.

Can you attach a small Code snippet?

**Comment by peacechen** [comment]
Could you clarify your requirements?  If it's difficult to describe, an image mockup may help.

**Comment by maniac-tech** [comment]
> 
> 
> Could you clarify your requirements? If it's difficult to describe, an image mockup may help.

I want the Calendar to open with a default date of `Today`

**Comment by peacechen** [comment]
Your code snippet should work:
```
<CalendarPicker
  selectedStartDate={moment()}
  onDateChange={this.dateChanged}
/>
```

The default month that it opens to is the initialDate prop, which is "today".  `selectedStartDate` marks the date as selected.

**Comment by venkat-waran** [comment]
Hi @peacechen ,

`<CalendarPicker
            startFromMonday
            todayBackgroundColor="#fff"
            todayTextStyle={{
              color: moment().isSame(selectedDate, 'day')
                ? '#05C976'
                : colors.black,
            }}
            selectedDayTextColor="#05C976"
            selectedDayStyle={{
              backgroundColor: colors.white,
            }}
            disabledDatesTextStyle={{ color: '#AAAAAA' }}
            dayLabelsWrapper={{
              borderTopWidth: 0,
              borderBottomWidth: 0,
              paddingTop: wp(4),
              paddingBottom: wp(4),
            }}
            weekdays={['M', 'T', 'W', 'T', 'F', 'S', 'S']}
            onDateChange={handleDateSelect}
            selectedStartDate={moment()}
          />`

I'm using selectedStartDate. But still, I'm not able to see default selected in the calendar.

Am I missing anything?
![Screenshot 2020-08-11 at 7 41 55 PM](https://user-images.githubusercontent.com/6994599/89907934-e6e87880-dc0a-11ea-8d22-d8e42fe1081f.png)
