### ISSUE TITLE
month select disabled logic

### ISSUE THREAD

**Issue by web-dev-s** [stephy/CalendarPicker#216]
@ Month.js, line 30, I think you are missing this:

 // Check whether month is outside of min/max range.
  if (maxDate && (year === maxDate.year())) {
    monthIsAfterMax = month > maxDate.month();
  }
  if (minDate && (year === minDate.year())) {
    monthIsBeforeMin = month < minDate.month();
  }

, otherwise even in range interval month selection will be disabled....

and at MonthSelector.js (line 34) at header..is nicer to know for which year you select the month:

 <MonthsHeader
          styles={styles}
          textStyle={textStyle}
          title={title + ' ' + currentYear}
          headingLevel={headingLevel}
        />

**Comment by peacechen** [comment]
Thanks @web-dev-s for tracking down that bug.  I'll fix those and publish a new version.

**Comment by peacechen** [comment]
Your fix has been released in 7.0.0.

Note that you can customize the select month header with the prop `selectMonthTitle` if you prefer different text. The year will be appended to that.
