### ISSUE TITLE
npm i {dependency} does not work after calendarPicker

### ISSUE THREAD

**Issue by richardszanyi** [stephy/CalendarPicker#217]
Today I was needed to install another dependancy to our project. Hence, I used:
![image](https://user-images.githubusercontent.com/9089337/87871744-650e8200-c9b3-11ea-932b-46f5a70a3c16.png)

Then, I was ok - then I'll just remove node_modules, and install then. 
I did, npm i worked with safe-area-context, it is added to package.json. 
Okay, I was like now I can use npm i to resolve the rest of the dependancies: 

![image](https://user-images.githubusercontent.com/9089337/87871760-8a02f500-c9b3-11ea-87aa-6f6dcac3846d.png)

So I removed node_modules again, then ran 'npm i'. 

It worked, and dependencies are resolved. 

It concerns me that somehow calendar-picker bugs out with npm dependency resolve, and cannot install any more after installing it.

**Comment by peacechen** [comment]
Thanks for reporting this issue.  Do you have a history of the exact versions of `react-native-calendar-picker` installed?  Depending on the type of version specified in package.json, package-lock.json or yarn.lock would record specific versions.  Older versions of either `react-native-calendar-picker` or its dependency `node-git-hooks` had a bug that may be related.  To confirm this, would you test adding another new package?

**Comment by richardszanyi** [comment]
package-lock has a version 6.1.2, as well as package.json specified. 
New package adding is throwing error still: 
![image](https://user-images.githubusercontent.com/9089337/88030022-05db7980-cb3b-11ea-89c1-715badc89f2a.png)

**Comment by peacechen** [comment]
The git hooks installation was fixed in 6.1.5.  I recommend that you upgrade to 7.0.0 and delete package-lock to ensure that all its dependencies are up to date.

**Comment by richardszanyi** [comment]
![Jegyzet_2020-07-22_124033](https://user-images.githubusercontent.com/9089337/88167119-a05dba80-cc18-11ea-82d5-04eafdff16b8.jpg)
This is with 7.0.0

**Comment by peacechen** [comment]
That sounds like a stale cache issue.  Use these steps to clear the cache:

1. Delete node_modules.
2. `npm install`
3. `npm start -- --reset-cache`
4. Break out of that after it starts the packager: `Ctrl-C`.
5. Start the app with `npm start` (or `react-native run-...` for native projects).

The `--reset-cache` flag requires @react-native-community/cli-tools:
> npm install @react-native-community/cli-tools --global

In the future, please paste the logs as text instead of a screenshot.  That makes it easier to copy/paste the contents to search.
