### ISSUE TITLE
Bug previousComponent/nextComponent

### ISSUE THREAD

**Issue by JanaMineur-r0663200** [stephy/CalendarPicker#223]
If I understand correctly, if I specify a `previousComponent` or `nextComponent`, this will override the default title 'Next' and 'Previous'. But this seems not to work?

```
<CalendarPicker
          initialDate={selectedDate}
          selectedStartDate={selectedDate}
          onDateChange={_onDateChange}
          weekdays={moment.weekdaysShort(true)}
          months={moment.months()}
          selectedDayTextColor={Colors.white}
          selectedDayColor={Colors.primary}
          previousComponent={
            <ChevronLeft width={30} height={30} color={Colors.gray} />
          }
          nextComponent={
            <ChevronRight width={30} height={30} color={Colors.gray} />
          }
          startFromMonday
/>
```

I still get the default titles _next_ and _previous_?

The only workaround is to pass the icons to the `previousTitle` and `nextTitle` props, this works but I'm using typescript so I get a typescript error because i'm not passing a string.

**Comment by Roka20012** [comment]
Hey @JanaMineur-r0663200  👋

I am using it in the same as you, and it works well for me
