### ISSUE TITLE
disable all dates prior to the current date

### ISSUE THREAD

**Issue by geraldo-thorpe-innovation** [stephy/CalendarPicker#227]
Is there any way to disable previous dates, compared to my current date? At the moment, I cannot allow my user to select dates from the past.

**Comment by geraldo-thorpe-innovation** [comment]
This code resolve my problem: 

**in this part, we take all the dates prior to the current day, and we add there is a state:**
```
let date = new Date()
const test = date.setDate(new Date().getDate() - 1)

 setPriorDates(test)
```



```
<CalendarPicker
   ...
   disabledDates={[priorDates]}
```

**Comment by peacechen** [comment]
`disabledDates` also accepts a function.  You could use it like this to disable dates before today:

```
const today = moment();

<CalendarPicker
   disabledDates={date => date.isBefore(today, "day")}
   //...
/>
```
