### ISSUE TITLE
onChangeDate not working in hooks

### ISSUE THREAD

**Issue by Shahanshah87** [stephy/CalendarPicker#229]
`<CalendarPicker
                        startFromMonday={true}

                        allowRangeSelection={true}

                        minDate={minDate}

                        maxDate={maxDate}

                        todayBackgroundColor={constants.Colors.color_161758}

                        selectedDayColor={constants.Colors.color_ff8148}

                        selectedDayTextColor="#FFFFFF"

                        onDateChange={() => onDateChange()}

                    />`

function onDateChange:- 
       `const onDateChange = (date, type) => { 
         console.log(date, type); 
          if (type === 'END_DATE') { 
            setData({ 
                ...data, 
                booking_to:date, 
            }) 
          } else { 
            setData({ 
                ...data, 
                booking_from:date, 
            })
          }
       }`

I am unable to understand what should I pass as arguement in 
`onDateChange={() => onDateChange(WHAT ARGUEMENT SHOULD BE PASSED HERE?)}`

**Comment by Shahanshah87** [comment]
@stephy @peacechen

**Comment by Roka20012** [comment]
Hey @Shahanshah87 👋

Could please tell me what exactly doesn't work?

Have you got any errors?

It works well for me

![Screenshot 2020-08-18 at 15 30 54](https://user-images.githubusercontent.com/32239452/90513135-dc2c6700-e167-11ea-84da-f3778a3c601e.png)
<img width="315" alt="Screenshot 2020-08-18 at 15 31 00" src="https://user-images.githubusercontent.com/32239452/90513142-dd5d9400-e167-11ea-81b8-0a64217ad7cf.png">

**Comment by peacechen** [comment]
@Shahanshah87  Refer to the example app:
https://github.com/stephy/CalendarPicker/blob/master/example/App.js#L129

**Comment by Shahanshah87** [comment]
@Roka20012 
if you use this in class component, it will work fine but when you use this in functional component.
and call the function `onDateChange={() => onDateChange()}` and `const onDateChange = (date, type) => { console.log(date, type); if (type === 'END_DATE') { setData({ ...data, booking_to:date, }) } else { setData({ ...data, booking_from:date, }) } }` then in log `date` and `type` comes undefined.

**Comment by peacechen** [comment]
@Shahanshah87 
You're not passing any parameters to your `onDateChange` callback.  It's unnecessary to create an anonymous function:
```
onDateChange={() => onDateChange()}
```

Refer to the example app that I linked above.
