### ISSUE TITLE
Support Android

### ISSUE THREAD

**Issue by jcmartins** [stephy/CalendarPicker#23]
Hi,
do you have plans to CalendarPicker in android?

obrigado,
joão

**Comment by luisfuertes** [comment]
CalendarPicker actually runs on android.

**Comment by jcmartins** [comment]
Hi I'm having this error:
Element type is invalid: expected string (for built-in components) or a class/function ( for composite components) but got: object.

**Comment by jcmartins** [comment]
@luisfuertes 
you are right! 
I tried it and it's ok!!!

tks
João
