### ISSUE TITLE
Using restrictMonthNavigation prop without maxDate prop?

### ISSUE THREAD

**Issue by Roka20012** [stephy/CalendarPicker#230]
Hey guys 👋

When I trying to select a year without providing `maxDate` prop I am getting this error.
So I need `restrictMonthNavigation` for past dates but not for future dates

**Question ❓**  
> How I can use `restrictMonthNavigation` for past dates without providing  `maxDate` because without it I also getting this bug [month shifting bug](https://github.com/stephy/CalendarPicker#scrollable-calendarpicker--new-in-7x)

**Error 🚨**
> ![image](https://user-images.githubusercontent.com/32239452/90516107-37f8ef00-e16c-11ea-9cb0-c8b460052aa2.png)

**Code 👨‍💻** 
```js
<CalendarPicker
    onDateChange={onChangeDate}
    restrictMonthNavigation
    weekdays={WEEKDAYS}
    minDate={minDate}
    scrollable
/>
```

**Video 🎬**
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/32239452/90517226-c7eb6880-e16d-11ea-9731-c9c3be0ff087.gif)

**Comment by peacechen** [comment]
Thanks for reporting this bug.  If you have time to debug this, please submit a PR and I'll merge right away.

**Comment by saaketnarnolia** [comment]
I am facing this error too.

**Comment by peacechen** [comment]
This may be the problem in YearsHeader.js:
```
  const disablePrevious = restrictNavigation && (minDate.year() >= year);
  const disableNext = restrictNavigation && (maxDate.year() <= year);
```
https://github.com/stephy/CalendarPicker/blob/master/CalendarPicker/YearsHeader.js#L31

It should check for valid minDate and maxDate, e.g.
```
  const disableNext = restrictNavigation && maxDate && (maxDate.year() <= year);
```

Please test that and submit a PR if it works.
