### ISSUE TITLE
TypeError: Cannot read property 'year' of undefined when pressing on year part of MonthYearTitle

### ISSUE THREAD

**Issue by MannySAD** [stephy/CalendarPicker#231]
As the title states, when I press on the year side of the MonthYearTitle it throws this error. But works perfectly fine when I press months. I didn't find a `year` prop where I could declare the years or anything of that sort, so im a bit confused, The only thing I guess could be a problem is the fact that im passing a moment date to maxDate & initialDate.

My use of the picker component:

 ```
<CalendarPicker
    allowRangeSelection={true}
    maxDate={maxDate}//maxDate is moment().format("YYYY-MM-DD");
    weekdays={weekdays}
    months={months}
    initialDate={maxDate}
    selectMonthTitle={"Selecciona mes de "}
    selectYearTitle={"Seleccionar año"}
    previousTitle="Anterior"
    nextTitle="Próximo"
    restrictMonthNavigation={true}
    todayBackgroundColor={'#fff'}
    selectedDayColor={Orange_PRIMARY}
    selectedDayTextColor="#fff"
    allowBackwardRangeSelect={true}
    scaleFactor={375}
    startFromMonday={true}
    todayTextStyle={{color: 'green'}}
    onDateChange={onDateChange}
/>
```

Screen shot of the error:
 
![Screenshot_20200821-234035 1](https://user-images.githubusercontent.com/33158848/90949863-a5757b80-e409-11ea-8eeb-1c5b0047474e.png)

**Comment by peacechen** [comment]
This should be fixed in commit 497c8c0aee768fa919eb7399b85a08b1d9a489d9
