### ISSUE TITLE
How to deselect a day from a range?

### ISSUE THREAD

**Issue by dariocostanzo** [stephy/CalendarPicker#232]
Hi, is there a way to remove a day (or more) from a range? For example if the selected range goes from Monday to Friday I want to be able to exclude Tuesday and Thursday. 

In alternative, would be possible to select a range day by day, rather than from start to end?

Thanks

**Comment by dariocostanzo** [comment]
@peacechen help please

**Comment by dariocostanzo** [comment]
Closing it due to lack of support.

**Comment by peacechen** [comment]
This has been requested previously in #121 

This is a community supported library and contributions are welcome. Please submit a PR for new features or bug fixes.
