### ISSUE TITLE
Issue in migrating from @6.1.4 to @7.0.0

### ISSUE THREAD

**Issue by saaketnarnolia** [stephy/CalendarPicker#233]
Getting this issue when migrated from @6.1.4 to @7.0.0

Loading dependency graph...error Unable to resolve module `./Swiper` from `/Volumes/workplace/INPayments/src/INPaymentsMerchantAppCoreJS/node_modules/react-native-calendar-picker/CalendarPicker/index.js`: The module `./Swiper` could not be found from `/Volumes/workplace/INPayments/src/INPaymentsMerchantAppCoreJS/node_modules/react-native-calendar-picker/CalendarPicker/index.js`. Indeed, none of these files exist:
  * `/Volumes/workplace/INPayments/src/INPaymentsMerchantAppCoreJS/node_modules/react-native-calendar-picker/CalendarPicker/Swiper(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Volumes/workplace/INPayments/src/INPaymentsMerchantAppCoreJS/node_modules/react-native-calendar-picker/CalendarPicker/Swiper/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`. Run CLI with --verbose flag for more details.

**Comment by peacechen** [comment]
Swiper was deprecated due to the introduction of `scrollable`.  That error is usually caused by stale node_modules or packager's cache.

https://github.com/stephy/CalendarPicker/issues/217#issuecomment-662475755

**Comment by saaketnarnolia** [comment]
Sure, will try to check it today and update here.

**Comment by saaketnarnolia** [comment]
I am able to integrate now. Thanks 👍
