### ISSUE TITLE
allowRangeSelection with minRangeDuration=1

### ISSUE THREAD

**Issue by skulegirl** [stephy/CalendarPicker#238]
I have allowRangeSelection=true, and want to require that startDate != endDate. However setting minRangeDuration=1 does not prevent the user from selecting endDate the same as startDate. I can disable the startDate via disabledDate after it's selected, but then it does not appear as selected in the calendar.

**Comment by peacechen** [comment]
Does `minRangeDuration=2` work for your use case?

**Comment by skulegirl** [comment]
No, if I do that then it requires endDate be at least 2 days after startDate. I need endDate = startDate +1 to be acceptable.

**Comment by peacechen** [comment]
That's a bug. This section looks like it handles the range selectability:
https://github.com/stephy/CalendarPicker/blob/7a3e6eb6c0fb3322285b48b3a4684f196c9f42d7/CalendarPicker/Day.js#L85

Would you mind testing and submitting a PR?
