### ISSUE TITLE
Please add a way to have custom year i.e. buddhist year

### ISSUE THREAD

**Issue by bpetrified** [stephy/CalendarPicker#239]
Is it possible to add a prop like "customYear" which will be a function that allows transforming from christian year to buddhist (2020 -> 2543) ?

Thank you very much!

**Comment by peacechen** [comment]
This is a community supported library and your contributions are welcome.

You could either add a new prop to support Buddhist years, or compensate for the difference in your application code and pass the adjusted Moment object to CalendarStrip.  Here's an example:
https://gist.github.com/akexorcist/eb5e8266670721c191a62851e3d8bb3d

There was a PR submitted to the Moment library to add Buddhist years, but they deemed it too complicated to merge.
https://github.com/moment/moment/pull/874
