### ISSUE TITLE
customDayHeaderStylesCallback  = {}

### ISSUE THREAD

**Issue by methineeinkan** [stephy/CalendarPicker#241]
const customDayHeaderStylesCallback = dayOfWeek => {
    switch (dayOfWeek) {
      case 7:
        return {
          textStyle: {
            color: '#FE6202',
          },
        };
      case 6:
        return {
          textStyle: {
            color: '#FE6202',
          },
        };
    }
  }; 

not work

**Comment by yousefhossein** [comment]
Thank you i solv the problem


در تاریخ دوشنبه ۱۲ اکتبر ۲۰۲۰،‏ ۱۰:۳۲ VIKING <notifications@github.com>
نوشت:

**Comment by methineeinkan** [comment]
use switch (dayOfWeek.dayOfWeek) lol

**Comment by peacechen** [comment]
Thanks for noting this.  Would you mind updating the Readme?
