### ISSUE TITLE
Warning: Failed prop type: DaysGridView: prop type `selectedRangeEndStyle` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.

### ISSUE THREAD

**Issue by ajengrf** [stephy/CalendarPicker#246]
I'm using React Native v0.63.2 and got this warning with the calendar but I do know how to solve it. I hope anyone can give me solution. I'm following the same code from documentation: 
```
<CalendarPicker
    ref={ref}
    startFromMonday={true}
    allowRangeSelection={true}
    minDate={minDate}
    maxDate={maxDate}
    todayBackgroundColor={colors.secondary}
    selectedDayColor={colors.primary}
    selectedDayTextColor={colors.background}
    scaleFactor={385}
    textStyle={styles.textStyle}
    onDateChange={onDateChange}
    restrictMonthNavigation
/>
```
and got this error: 
![Screen Shot 2020-10-23 at 06 55 17](https://user-images.githubusercontent.com/30023314/96942035-2d592e00-14fe-11eb-8bec-bd7fae65761a.png)

**Comment by pablogarayprosis** [comment]
same problem here

**Comment by peacechen** [comment]
The prop type for `selectedRangeEndStyle` does not specify it as required. That error doesn't make sense.

https://github.com/stephy/CalendarPicker/blob/b93ae2ee9b762f2fa6e446d0c86003d21197faf8/CalendarPicker/DaysGridView.js#L257

**Comment by Margaferrez** [comment]
The same happens to me. It started happening when I migrated my project to typescript.
That is my call
               ```
 <CalendarPicker
                    style={styles.calendar}
                    startFromMonday={true}
                    weekdays={weekdays}
                    months={months}
                    previousTitle={translations['previous']}
                    nextTitle={translations['next']}
                    selectedDayColor="#6B9662"
                    selectedDayTextColor="#000000"
                    onDateChange={onDateChange}
                    />
```
And I get four different warnings:

- Warning: Failed prop type: DaysGridView: prop type `selectedDayStyle` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`. 
- Warning: Failed prop type: DaysGridView: prop type `selectedRangeStartStyle` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`. 
- Warning: Failed prop type: DaysGridView: prop type `selectedRangeStyle` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`. 
- Warning: Failed prop type: DaysGridView: prop type `selectedRangeEndStyle` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`. 

And those are my versions:
    "react-native": "0.63.3",
    "react-native-calendar-picker": "^7.0.2"

**Comment by JaccoM** [comment]
Same happens to me, is there a solution for this?

`        <CalendarPicker
          startFromMonday={true}
          scrollable={true}
          weekdays={['M', 'D', 'W', 'D', 'V', 'Z', 'Z']}
          minDate={minDate}
          maxDate={maxDate}
          todayBackgroundColor={theme.colors.green}
          selectedDayColor={theme.colors.slateblue}
          selectedDayTextColor={theme.colors.white}
          restrictMonthNavigation={true}
          previousComponent={this.renderPrevious()}
          nextComponent={this.renderNext()}
          onDateChange={this.onDateChange}
          textStyle={{
            fontFamily: 'SourceSansPro-Bold',
            color: theme.colors.slateblue,
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: 16,
          }}
          dayLabelsWrapper={{
            borderBottomWidth: 0,
            borderTopWidth: 0,
            margin: -6,
          }}
        />`

The warnings I get are these 4:

- Warning: Failed prop type: `DaysGridView`: prop type `selectedDayStyle` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
- Warning: Failed prop type: `DaysGridView`: prop type `selectedRangeStartStyle` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
- Warning: Failed prop type: `DaysGridView`: prop type `selectedRangeStyle` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
- Warning: Failed prop type: `DaysGridView`: prop type `selectedRangeEndStyle` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.

**Comment by Trujillo19** [comment]
I have the same warnings. But It doesn't seems to affect anything else.

What would happened if I left it there?

**Comment by LudoLamerre** [comment]
I have the same warnings ... It started to happen without any changes in this component ...
Has anyone found a solution?
`      <CalendarPicker
              {...{minDate, maxDate}}
              ref={calendarRef}
              startFromMonday={true}
              weekdays={weekdays}
              months={months}
              customDayHeaderStyles={() => {
                return {
                  style: styles.weekView,
                  textStyle: styles.weekTextStyle,
                };
              }}
              previousComponent={
                <NextPreviousIcon
                  fill={colors.blue}
                  style={{
                    transform: [
                      {rotate: I18nManager.isRTL ? '180deg' : '0deg'},
                    ],
                  }}
                />
              }
              nextComponent={
                <NextPreviousIcon
                  fill={colors.blue}
                  style={{
                    transform: [
                      {rotate: I18nManager.isRTL ? '0deg' : '180deg'},
                    ],
                  }}
                />
              }
              todayBackgroundColor={colors.grey}
              selectedDayTextColor="white"
              selectedDayColor={colors.blue}
              textStyle={calendarText}
              initialDate={date}
              restrictMonthNavigation
              onDateChange={onSelectDate}
              customDatesStyles={customDatesSelectedCallback}
              dayLabelsWrapper={{
                borderBottomWidth: 0,
                borderTopWidth: 0,
              }}
            />`

**Comment by rossenv** [comment]
No problems when downgraded to 7.0.1

**Comment by peacechen** [comment]
Would someone submit a PR to fix the prop-types and/or the TS definition file?

**Comment by Margaferrez** [comment]
> Would someone submit a PR to fix the prop-types and/or the TS definition file?

I've fixed it locally, I can send a PR, can you give me permissions to do it? Thanks

**Comment by peacechen** [comment]
@Margaferrez 
Fork this repo, commit your changes, then submit a PR through Github. No extra permissions required to do that.

**Comment by peacechen** [comment]
Thanks @Margaferrez for fixing this 👍 

7.0.3 has been published
