### ISSUE TITLE
Invalid prop `customDatesStyles` supplied to `DaysGridView`.

### ISSUE THREAD

**Issue by shashankcomfort** [stephy/CalendarPicker#252]
![Screenshot 2020-11-11 at 1 11 37 PM](https://user-images.githubusercontent.com/61941226/98783391-7b879000-241f-11eb-8144-80ba4a2b22ae.png)

**Comment by peacechen** [comment]
Which version of CalendarPicker are you using? Please post a code snippet of your `<CalendarPicker />` usage.
