### ISSUE TITLE
[Warning]: failed prop type: DaysGridView: prop type 'selectedRangeEndStyle' is invalid; it must be a function -

### ISSUE THREAD

**Issue by MannySAD** [stephy/CalendarPicker#255]
- usually from the 'prop-types' package, but recieved 'undefined'. in DaysGridView at CalendarPicker/index.js

I got this warning after updating the calendarPicker package, whenever I open the picker... I haven't noticed if it affects anything, but its something to keep in mind maybe.. 
my code:

<CalendarPicker
          allowRangeSelection={multiple}
          maxDate={maxDate}
          minDate={minDate} 
          weekdays={weekdays}
          months={months}
          initialDate={initialDate || maxDate}
          selectedStartDate={initialDate}
          selectMonthTitle={'Selecciona mes de '}
          selectYearTitle={'Seleccionar año'}
          previousTitle="Anterior"
          nextTitle="Próximo"
          restrictMonthNavigation={true}
          todayBackgroundColor={'#fff'}
          selectedDayColor={PRIMARY}
          selectedDayTextColor="#fff"
          allowBackwardRangeSelect={true}
          scaleFactor={375}
          height={420}
          startFromMonday={true}
          todayTextStyle={{color: 'green'}}
          onDateChange={onDateChange}
        />

**Comment by peacechen** [comment]
Fix in 7.0.4
