### ISSUE TITLE
PropTypes.undefined doesn't exist in prop types

### ISSUE THREAD

**Issue by n-sviridenko** [stephy/CalendarPicker#256]
The version 7.0.3 is buggy, please revert that change. Thanks

**Comment by n-sviridenko** [comment]
Also, `Text.propTypes.style` fails (because `Text.propTypes` is `undefined`) in the environment where propTypes are removed (e.g. production). So I'm unable to run my storybook which does it.

**Comment by peacechen** [comment]
Please try 7.0.4.  If there's still an issue, please provide a link to the line that is causing the error.

**Comment by peacechen** [comment]
This should be fixed in 7.0.6
