### ISSUE TITLE
Is it possible to disable dates for all Sundays? 

### ISSUE THREAD

**Issue by rikinshah23** [stephy/CalendarPicker#257]
Thanks for this great package. 

I am using it for amenity booking. 
If an Amenity closed for booking on any day of week, how do I disable all dates for Sunday using this control ? 
Or any other suggestion that makes it easier for me to accomplish this task ? 

Thanks

**Comment by rikinshah23** [comment]
Actually I was able to find all dates for Sundays and provide the array into disabledDates prop. 
Closing the issue.

**Comment by aravicubet** [comment]
@rikinshah23  how do you managed to find sundays? Could you please share the code

**Comment by peacechen** [comment]
To act on day for all weeks, it's easier to pass a function to `disabledDates`
> Specifies dates that cannot be selected. Array of Dates, or a function that returns true for a given Moment date

Refer to the example app in this project.

**Comment by aravicubet** [comment]
@peacechen  Thanks for the help. I was able to mange that, but the date looks disabled but the selection is still there. how to make the selection only appear to enabled dates?
<img width="325" alt="Screenshot 2021-08-09 at 1 38 13 PM" src="https://user-images.githubusercontent.com/82430019/128676392-b982d46a-b0af-4b96-a951-306388ec3b7e.png">
