### ISSUE TITLE
More day options for start of the week

### ISSUE THREAD

**Issue by elliscwc** [stephy/CalendarPicker#266]
thanks for the wonderful calendar picker

I would like to request a feature so that picker can show start of the week for any days instead of just Monday, currently the picker supports `startFromMonday` but it is kind of limit what the user can do.

**Comment by peacechen** [comment]
Please submit a PR to add that feature. Take a look at how `startFromMonday` is implemented, and you should be able to enhance that to start from any day of the week.

**Comment by peacechen** [comment]
Published in 7.1.1

**Comment by elliscwc** [comment]
thanks @peacechen  🙂
