### ISSUE TITLE
Can I disable All Sunday from calender?

### ISSUE THREAD

**Issue by sudippalash** [stephy/CalendarPicker#267]

**Comment by peacechen** [comment]
Use the `disabledDates` prop and pass a callback function to it. In your callback, check if the date is a Sunday and return true.
https://github.com/stephy/CalendarPicker#calendarpicker-props

**Comment by sudippalash** [comment]
That means there is no option for off day object or array like {'Sunday', 'Saturday'}

**Comment by peacechen** [comment]
There are many other use cases that a simple array does not handle. For example, every other Sunday, leap days, beginning of month, end of month, a specific day of the month, etc. A function to determine the day of week is trivial.
