### ISSUE TITLE
initialDate not working

### ISSUE THREAD

**Issue by agunbuhori** [stephy/CalendarPicker#268]

**Comment by peacechen** [comment]
Please try the demo project in this repo:
https://github.com/stephy/CalendarPicker#sample-application

It would help if you could provide a <CalendarPicker> snippet from that demo that recreates the error.

**Comment by vvdwivedi** [comment]
If we set an initialDate, it is generally expected to be highlighted. But when we open the calendar, this is not highlighted.

**Comment by innonguyen** [comment]
I had the same issue. InitialDate doesn't receive the right date. Always return today.

**Comment by peacechen** [comment]
`initialDate` sets which date (month) that the calendar opens to. `selectedStartDate` highlights the selected date.
