### ISSUE TITLE
calender not loading and crashes in some devices 

### ISSUE THREAD

**Issue by hackerfrks** [stephy/CalendarPicker#275]
![Screenshot from 2021-03-31 16-30-21](https://user-images.githubusercontent.com/24808660/113134489-7a27fa00-923e-11eb-9296-12fe7fe1dfb2.png)

**Comment by hackerfrks** [comment]
it was working good till today .suddently users can't enter into calender page . no changes in code as we have this issue on our production app

**Comment by peacechen** [comment]
What was the problem?
