### ISSUE TITLE
Clear feature - If user selects the wrong start date, then he/she has to select an end date before they can select the correct start date.  

### ISSUE THREAD

**Issue by davidfeldt** [stephy/CalendarPicker#277]
Having a clear feature would be great.  

I added a "clear" button which sets startDate and endDate to null but the calendar still shows the old selected range after clearing startDate and endDate.

**Comment by peacechen** [comment]
Please post a sample with your clear button. You can use the sample app in this project as a base.
https://github.com/stephy/CalendarPicker#sample-application

This library checks for `selectedStartDate` and `selectedEndDate` prop updates that your component passes in:
https://github.com/stephy/CalendarPicker/blob/master/CalendarPicker/index.js#L77

**Comment by davidfeldt** [comment]
Here's the test I ran: https://github.com/davidfeldt/test-calendar-picker.git

When you tap "Clear dates", it sets the dates to null but the range is still visible in the calendar.

![Simulator Screen Shot - iPhone 11 - 2021-04-03 at 11 56 50](https://user-images.githubusercontent.com/598769/113511493-13505c80-952e-11eb-84bb-368a7b786aaa.png)
![Simulator Screen Shot - iPhone 11 - 2021-04-03 at 11 57 02](https://user-images.githubusercontent.com/598769/113511502-1a776a80-952e-11eb-9b27-8a4416102fc4.png)
![Simulator Screen Shot - iPhone 11 - 2021-04-03 at 11 57 13](https://user-images.githubusercontent.com/598769/113511509-1f3c1e80-952e-11eb-9a3f-e0d7edbe0ba2.png)

**Comment by davidfeldt** [comment]
Here's the test I ran: https://github.com/davidfeldt/test-calendar-picker.git

When you tap the "Clear dates" button, it clears the dates but the date range is still visible on the calendar.

See below:
![Simulator Screen Shot - iPhone 12 - 2021-04-04 at 10 08 06](https://user-images.githubusercontent.com/598769/113511576-65917d80-952e-11eb-88ab-841529b7caed.png)
![Simulator Screen Shot - iPhone 12 - 2021-04-04 at 10 08 58](https://user-images.githubusercontent.com/598769/113511581-6e824f00-952e-11eb-83f8-e3dba7cc96a2.png)
![Simulator Screen Shot - iPhone 12 - 2021-04-04 at 10 09 13](https://user-images.githubusercontent.com/598769/113511587-74783000-952e-11eb-8382-9e421cd650e2.png)

**Comment by davidfeldt** [comment]
Ok, I added:

selectedStartDate={selectedStartDate}
selectedEndDate={selectedEndDate}

and now it works correctly.
