### ISSUE TITLE
Since react-native 26, onDateChange always called with previously selected date or today date

### ISSUE THREAD

**Issue by huston007** [stephy/CalendarPicker#29]
1. react-native 0.26.3 is used
2. Click any day in calendar and check what date is passed to `onDateChange` callback: it is always the date which was selected before tap.

Looks like is already fixed in fork https://github.com/jak4/CalendarPicker/commit/ffb5b71a2223de84a84ab0cbb56a7f82a1b8aede

So, @jak4, let's PR that work maybe?

**Comment by colinyoung** [comment]
@jak4 and @huston007 - I pushed a PR related to this issue here: #34. The commit referenced above would also solve the problem, but introduces larger changes to the codebase.

**Comment by ademars94** [comment]
@huston007 @jak4 I just submitted a pull request with some corrections.  Tested and working on my machine.

**Comment by diogoviannaaraujo** [comment]
having this issue too..

**Comment by ademars94** [comment]
@diogoviannaaraujo Check out my pull request.  Issue is fixed, just waiting for my pull req to merge.

**Comment by stephy** [comment]
I believe this has been completely fixed on v5.
