### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by tuckerchapin** [stephy/CalendarPicker#33]
It may just be me, but it seems that this component is extremely slow. There is a significant and noticeable delay between clicking a date and having it register on screen. There's a minor lag using the iOS emulator, but it is extremely noticeable to the point of being a hindrance on a real device (6S+).

I was just wondering if this was an issue people were aware of or others were experiencing or if I was alone in this.

**Comment by jak4** [comment]
You are probably running the app in Development mode on the device. Try running it in Release mode and it should be considerably faster, still not really that fast, but comparable to the emulator in dev mode.

**Comment by yeknava** [comment]
@tuckerchapin check my [pull request](https://github.com/stephy/CalendarPicker/pull/52/commits/fa111265a80c08db534ad57739a2af684d373723)

**Comment by peacechen** [comment]
The click delay lag is high.  Hope @tuckerchapin 's PR speeds it up.

**Comment by yeknava** [comment]
@peacechen check my fork, it fixed performance issue by removing an unnecessary 'for'.
btw as she said she rewrote whole library in version 2 (i didn't test it yet).

**Comment by peacechen** [comment]
The click lag is due to my app's internal state updates and not CalendarPicker.  v5 performance is good.
