### ISSUE TITLE
Heading Text Color not working?

### ISSUE THREAD

**Issue by justdan0227** [stephy/CalendarPicker#338]
What am I missing when attempting to change the heading text color to white?

`headerWrapperStyle: {
    backgroundColor: '#007acc',
    color: '#ffffff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 20,
  },`
![CleanShot 2023-01-30 at 10 15 53](https://user-images.githubusercontent.com/918740/215532189-6414011b-5bde-4c58-9cb3-5fb74b9b93b2.png)

**Comment by ShahidRas00l** [comment]
use props like this 
nextTitleStyle={{color:colors.whiteColor}}
          previousTitleStyle={{color:colors.whiteColor}}
          monthTitleStyle={{
            fontFamily: 'Cochin',
            color: colors.whiteColor,
          }}
          yearTitleStyle={{
            fontFamily: 'Cochin',
            color: colors.whiteColor,
          }}

**Comment by justdan0227** [comment]
Thanks!  Missed that
