### ISSUE TITLE
Adding the ability to customize the initial view

### ISSUE THREAD

**Issue by dmarcucci** [stephy/CalendarPicker#340]
See https://github.com/stephy/CalendarPicker/pull/339.

I'm implementing the picker in a form where I want the user to select date of birth. I think it would be more straightforward UX wise to have them start with selecting year then month / day. However, I wasn't able to find a current prop that would allow this.

Seems it is just a matter of setting `currentView` in the state, so I just added a new prop to do so.

**Comment by dmarcucci** [comment]
Covered in https://github.com/stephy/CalendarPicker/pull/339, which has been merged.

**Comment by peacechen** [comment]
Thanks @dmarcucci 
This has been published on npm as v7.1.4
