### ISSUE TITLE
Replace moment with date-fns

### ISSUE THREAD

**Issue by tranjog** [stephy/CalendarPicker#360]
I believe there are good reasons to remove the peer dependency to [moment.js](https://github.com/moment/moment) and replacing it with [date-fns](https://date-fns.org/). Performance, bundle size, etc.

I have opened a PR here:
https://github.com/stephy/CalendarPicker/pull/359

Feel free to test it out and review it.

**Comment by peacechen** [comment]
Thanks for contributing!

The alpha version has been published to npm. The main version still shows up as 7.1.4 because the 8.0.0-alpha release is tagged as alpha. You can start using the alpha version in your project.
https://www.npmjs.com/package/react-native-calendar-picker?activeTab=versions

**Comment by tranjog** [comment]
This has now been released as version 8.0.0
