### ISSUE TITLE
Empty row Showing in Calendar Days View for October 2023

### ISSUE THREAD

**Issue by shubhamjadon** [stephy/CalendarPicker#378]
In CalendarPicker if firstDay(prop) is 0 and firstDay of Month lies on Sunday then instead of 5 rows 6 rows are rendered where 1st row is empty(or contains last month dates if showDayStragglers is true).

For reproducible example, Please refer: [Expo Snack](https://snack.expo.dev/@jadonshubham/calendarpickeremptyrow). (Go to October 2023 in Calendar)

Here is the screenshot of October 2023
<img width="336" alt="image" src="https://github.com/stephy/CalendarPicker/assets/35838512/93a1c00b-e7cc-46f6-96e1-6225e127e270">

**Comment by peacechen** [comment]
Fix published in 8.0.4

Thanks for the PR @shubhamjadon
