### ISSUE TITLE
calendar extends outside of Modal

### ISSUE THREAD

**Issue by ndao** [stephy/CalendarPicker#43]
The calendar extends outside container when used inside React `Modal` component. Setting screenWidth doesn't change anything.

![image](https://cloud.githubusercontent.com/assets/8940740/16899204/f1c538c8-4baf-11e6-93e1-449841cc705f.png)

**Comment by chrise86** [comment]
The other issue I'm having with using this in a modal is that `onDateChange` fires when you browse next/previous month, so you can't toggle the modal when a date is selected, and you have to use a button to close the modal, which is not ideal... :-/

**Comment by chrise86** [comment]
Did you find a solution to the overflow problem @ndao ?

**Comment by chrise86** [comment]
Looks like the example is wrong, you need to use `scaleFactor`:

```
scaleFactor={(Dimensions.get('window').width - 40) / 375}
```

**Comment by ndao** [comment]
@chrise86, no i didn't come to a solution. I did try to use scaleFactor but I don't want everything to scale down, just want the space between the numbers to be smaller.

**Comment by jfoc2009** [comment]
Hi, scaleDown is just working fine in all scenarios I have in different devices screens sizes.

**Comment by peacechen** [comment]
PR #73 should fix this as long as you pass height & width props to CalendarPicker.  #71 has further discussion on it.

**Comment by stephy** [comment]
This should have been fixed on the latest version published to npm v5.10.0, feel free to reopen this issue if you still run into this.
