### ISSUE TITLE
selectedDate changes when month changed

### ISSUE THREAD

**Issue by ssomnoremac** [stephy/CalendarPicker#46]
expected behavior -  would be that if you change the month then the `selectedDate` remains the same (out of view).

actual behavior - selected date follows you Oct. 15 -> Nov 15

The expected is how all OS calendars I've seen seem to work. I looked at this code briefly and had no thoughts on where to begin. Any suggestions?

**Comment by dhansiddh** [comment]
Hey @ssomnoremac i have fixed this issue at [https://github.com/dhansiddh/CalendarPicker](url). I will create a pull request of it. But until that you can use this forked repo for the fix.

**Comment by peacechen** [comment]
Thanks for the fix. Have you created a PR?  Searched for it but don't see one.
