### ISSUE TITLE
Wrong weekdays when applying startFromMonday={true}

### ISSUE THREAD

**Issue by ithieund** [stephy/CalendarPicker#49]
@stephy ,
Thank you very much for the awesome plugin.
But when applying startFromMonday={true}, the weekdays do not update accordingly. It stills the same as before so the date and weekdays does not match.

<img width="720" alt="date picker error" src="https://cloud.githubusercontent.com/assets/4217195/21517724/1035c79c-cd14-11e6-8988-bc9b4d5c853e.png">

Can you please fix this soon?
Thanks.

**Comment by stephy** [comment]
This has been fixed on Version 5. Let me know if you still have this issue.

**Comment by kuyarawa** [comment]
![image](https://user-images.githubusercontent.com/6049123/37428176-01b591de-27fe-11e8-99d3-75a1331ea8f5.png)

"react-native-calendar-picker": "^5.14.0"
@stephy still happening when using `startFromMonday={true}`

**Comment by peacechen** [comment]
PR #101 attempted to fix this.  @kvasbo do you have any insight into this?

**Comment by kvasbo** [comment]
Obviously not... ;) I tested my fix and it worked perfectly - could there be a timezone issue?

**Comment by kuyarawa** [comment]
yes I think there's timezone issue, I have different result when I set moment locale before rendering this component either to `fr` or `id` and `en`

**Comment by kuyarawa** [comment]
I've submit PR #112 it's a simple fix for this

**Comment by joelmora** [comment]
Any update on the https://github.com/stephy/CalendarPicker/pull/112 ? I am having issues when I am using another locale for my app

**Comment by peacechen** [comment]
I commented on @kuyarawa's PR that `isoWeekday` should called be conditionally based on the `startFromMonday` prop.  I'm not sure how this affects all use cases.  We need better test coverage.

Referencing the [Moment JS docs](https://momentjs.com/docs/#/get-set/weekday/):

> If the locale assigns Monday as the first day of the week, moment().weekday(0) will be Monday. If Sunday is the first day of the week, moment().weekday(0) will be Sunday.

Do the locales have differing settings for the first day of the week?

**Comment by joelmora** [comment]
I am using `en` and `es` locales, both starts on Sunday, and for the sake of the test I am setting `startFromMonday = false` to avoid additional variables and still have the error when I am switching between. So my guess is the same as @kuyarawa, a timezone issue maybe?.

Looking forward for this get resolved, I'll leave my calendar in `en` meanwhile which is a bummer :confused:

**Comment by peacechen** [comment]
I merged #112 so that it can get more testing.  Please try it with `startFromMonday` set to true / false along with different locales.  

Until it's published, you can use it by pointing the package.json directly to this repo.
```
  "dependencies": {
    "react-native-calendar-picker": "https://github.com/stephy/CalendarPicker"
    ...
  }
```

**Comment by peacechen** [comment]
`5.20.0` has been published on npm 🍻

**Comment by fawazahmed-yara** [comment]
With:
```
startFromMonday={true}
```
I get correct old dates
![simulator_screenshot_2F7194B8-A57C-4D9F-9303-213D40DE23A7](https://user-images.githubusercontent.com/68209777/167680870-e34f9ed6-2c4f-4e1b-900b-b15f6ad2988f.png)

But without it, I get incorrect day:
![simulator_screenshot_BF22F682-BEF1-41E7-8F19-38594AAA0036](https://user-images.githubusercontent.com/68209777/167681006-efa2f676-b6b3-4308-af27-7dc5543e31ef.png)
