### ISSUE TITLE
[Support Request] How to mark a date with color

### ISSUE THREAD

**Issue by ithieund** [stephy/CalendarPicker#50]
Hi @stephy ,
Can we mark a certain date with a certain color?
For example: I'm having a meeting on 31 Dec 2016, this date should have red color.

If this feature is not available now, please add this feature in next release, I think it's easy for you as you marked the selected date with color already.
Thanks.

**Comment by peacechen** [comment]
This feature has been added on the master branch (see #98).  I plan to publish when it's had more testing & validation.

**Comment by peacechen** [comment]
This has been implemented and available on npm

**Comment by ithieund** [comment]
@peacechen ,
Thank you very much.
