### ISSUE TITLE
[Support Request] How to resize the height of dates

### ISSUE THREAD

**Issue by ithieund** [stephy/CalendarPicker#51]
Hi @stephy ,
The height of dates are too much so it's no room for other component below the date picker when running in the small devices. Ex: iPhone 4

How can I resize that height?
Thanks.

**Comment by peacechen** [comment]
PR #73 should fix this as long as you pass height & width props to CalendarPicker.  #71 has further discussion on it.

**Comment by stephy** [comment]
You can do that with the latest version published to npm (v5.10.0)
