### ISSUE TITLE
Open calendar to another date

### ISSUE THREAD

**Issue by peacechen** [stephy/CalendarPicker#57]
CalendarPicker opens to the current date by default.  Is there a way to get it to open to another date?  The use case is a date field that is pre-filled to an arbitrary date in the future, and opening the calendar picker should center to that date.  With CalendarPicker's current behavior of opening to the current date, the user has to potentially click through many months to get back to the pre-filled date.

**Comment by peacechen** [comment]
Upon examining the code, this could be implemented with a small change.  Expose initialDate as a prop, defaulting to the current date if it's not passed in.  Would you like a PR?

**Comment by clewiston** [comment]
I would also like to see this feature added.

**Comment by ittikorns** [comment]
+1

**Comment by peacechen** [comment]
Created PR #64 which implements this.

The calendar opens to the prop `initialDate` (defaults to today if not specified).  `initialDate` is not highlighted though.  That would need additional props to control styling, etc.

**Comment by stephy** [comment]
Hi @peacechen I merged your PR. Will update NPM shortly.
