### ISSUE TITLE
Have to subtract 1 from month for minDate?

### ISSUE THREAD

**Issue by kcfgl** [stephy/CalendarPicker#61]
I'm sure I'm just missing something silly, but if I try to set minDate like this 
`minDate={new Date(2017,4,17)}`

It sets the minimum date as May 17, 2017 instead of Apr 17, 2017.  It's easy enough to just do M-1, but before I do that I wanted to see if I'm missing something.

Awesome work BTW, best calendar component out there, so thank you!

**Comment by kcfgl** [comment]
You can probably ignore this for now. If I just do new Date() then it works fine. Only seems to be an issue if I try to set a specific date.

**Comment by stephy** [comment]
Hi @kcfgl the month should be an integer value beginning with 0 for January to 11 for December. 
Read here for more: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
