### ISSUE TITLE
TransformError Couldn't find preset "babel-preset-expo"

### ISSUE THREAD

**Issue by peacechen** [stephy/CalendarPicker#63]
I suspect this is the result of the addition to `.babelrc` of ```"presets": ["babel-preset-expo"]```.  Should this be added as a peer dependency?

**Comment by ittikorns** [comment]
+1, I'm experiencing this too when enable Hot Reloading

**Comment by peacechen** [comment]
This should get you back up and running:
`npm install babel-preset-expo --save`

Created PR #65 to add it to package.json

**Comment by ittikorns** [comment]
@peacechen I ran the command you gave me but still getting the error

This is what returns after run `npm install babel-preset-expo --save`
├── babel-preset-expo@1.0.1 
└── UNMET PEER DEPENDENCY react@16.0.0-alpha.6

**Comment by stephy** [comment]
This should have been fixed in the latest version published to npm (5.10.0)
