### ISSUE TITLE
error no demension set for key

### ISSUE THREAD

**Issue by hungdev** [stephy/CalendarPicker#68]
i run :  npm install --save react-native-calendar-picker  then react-native run-android, it says error like this

![er](https://cloud.githubusercontent.com/assets/12009276/25734774/848eef48-3190-11e7-9263-99ab8a09eacb.PNG)

**Comment by radishlau** [comment]
Same for me! Have you found a way to solve this yet?

**Comment by peacechen** [comment]
That looks like it's from Dimensions.get('window) on this line:
https://github.com/stephy/CalendarPicker/blob/master/CalendarPicker/index.js#L53

That should be supported on Android.  What version of RN are you using?
