### ISSUE TITLE
Duplicate module name: jsc-heap-capture

### ISSUE THREAD

**Issue by chibeepatag** [stephy/CalendarPicker#69]
My app won't start. I'm getting this error now.
Error: @providesModule naming collision:
  Duplicate module name: jsc-heap-capture

Help pls!

**Comment by urska19** [comment]
Installing v4 with `npm install git://github.com/stephy/CalendarPicker.git#v4 --save` instead of `npm install --save react-native-calendar-picker` resolves a couple of issues for me, including the one you mentioned.
