### ISSUE TITLE
Calendar overflows on smaller phones

### ISSUE THREAD

**Issue by coderdave** [stephy/CalendarPicker#7]
Out of the box, this is what the calendar looks like on the iPhone 5s simulators (and down):

![ios_simulator_-_iphone_4s_-_iphone_4s___ios_8_3__12f69_](https://cloud.githubusercontent.com/assets/964751/7221848/d8fabe6c-e6ca-11e4-8307-247bee577cc1.png)

How do I get it to fill the width of the screen without it overflowing on smaller phones?

I think a lot of it has to do with the hard coded widths in `Styles.js`.

I had *some* success by replacing the hard-coded widths in the wrappers with `justifyContent: 'space-between` but ran into some problems, mostly due to my inexperience with flex.

**Comment by stephy** [comment]
@coderdave this has been fixed in the latest package.
