### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by peacechen** [stephy/CalendarPicker#75]
@stephy 
The fix that moved React from dependencies to devDependencies isn't on npm, and it's causing repeated failures on the newer releases of RN:
https://github.com/facebook/react-native/issues/14302

It would be very helpful to publish the latest version to npm to prevent people from hitting this bug again and again.

**Comment by stephy** [comment]
@peacechen I published the latest master to npm, version 5.8.0.
