### ISSUE TITLE
Way to set selected dates to pre-populate on calendar when rendered

### ISSUE THREAD

**Issue by jnrepo** [stephy/CalendarPicker#76]
Wanted to know if there was a way to pre-populate selected dates?

**Comment by kcfgl** [comment]
Same here.  I don't want to switch to another calendar option, but it is important that I show already selected dates. Any thoughts would be appreciated.  Great calendar!

**Comment by peacechen** [comment]
#98 may provide the feature you need.  The selected date may be prepopulated with the `initialDate` prop.  Multiple selected dates would only make sense for range selection. Is that your use case?
