### ISSUE TITLE
[Support Request] How to add style the header next and previous elements?

### ISSUE THREAD

**Issue by tdimnet** [stephy/CalendarPicker#78]
Hi there,

I am working with this really cool library and I am having trouble with styling the header part. 
For instance, I would like to apply a rounded corner on the two title and I don't know if it is possible yet.

Thx,
Thomas.

**Comment by stephy** [comment]
I am working on giving the ability of having the entire calendar styled. This functionality should be coming soon on version 6.

**Comment by karimraoudy** [comment]
Hello , still no news about styling the header ?

**Comment by tdimnet** [comment]
Hello @karimraoudy : nope I do not.
So I prefered forking the project and modifying it directly :).

**Comment by peacechen** [comment]
PR's are welcome.  If you have the feature working on your fork, contribute back to the community :)

**Comment by vforvasile** [comment]
Add custom components, and style to headerControls [https://github.com/stephy/CalendarPicker/pull/169](https://github.com/stephy/CalendarPicker/pull/169)
