### ISSUE TITLE
UnableToResolveError

### ISSUE THREAD

**Issue by Clowning** [stephy/CalendarPicker#79]
Hi, Thanks for your component but i've this error after installed it.

Bundling: UnableToResolveError: Unable to resolve module `react/lib/LinkedStateMixin` from `/Users/user/Documents/Projets/ZProjects/app/mobile/project/node_modules/react-native-calendar-picker/node_modules/react-native/Libraries/react-native/react-native.js`: Module does not exist in the module map or in these directories:
  /Users/user/Documents/Projets/ZProjects/app/mobile/project/node_modules/react-native-calendar-picker/node_modules/react/lib
,   /Users/user/Documents/Projets/ZProjects/app/mobile/project/node_modules/react/lib
,   /Users/user/node_modules/react/lib

React-Native V : 0.45.1
React V : 15.6.1

Thanks :)

**Comment by cgberlin** [comment]
Having the same issue +1

**Comment by cgberlin** [comment]
@Clowning 

Here is what fixed it for me. 
Simply go into node_modules/react-native-calendar-picker and remove the node_modules folder in there.
Have had this issue with a few libraries.

**Comment by peacechen** [comment]
PR #84 fixes this and has been published to npm
