### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by SunSet1219** [stephy/CalendarPicker#80]
@stephy 
I installed react-native-calendar-picker using npm.
But it has any errors.
![image 2](https://user-images.githubusercontent.com/26632694/28772500-12d29ee2-75ef-11e7-9a25-61e2639400fa.png)
![image 4](https://user-images.githubusercontent.com/26632694/28772584-48aac490-75ef-11e7-81d6-c45e672fc6d4.png)

**Comment by Run-Snail** [comment]
+1

**Comment by Run-Snail** [comment]
Have you found a solution?

**Comment by yojolo** [comment]
+1
Happy to see that I'm not the only one... but it's kind of sad too

**Comment by rulgf** [comment]
Also the same problem. I think it has to be something related to #75 and #70.
Meanwhile try installing the `5.8.0` version

`npm install --save react-native-calendar-picker@5.8.0`

This version works for me

**Comment by aizigao** [comment]
the same question

**Comment by raynoppe** [comment]
I have the same problem

**Comment by aizigao** [comment]
reason is expo,  expo just cloud place in dependencies

**Comment by TyrealGray** [comment]
+1
RN:0.44.2
react-native-calendar-picker: 5.10.0

still no solution for this?

**Comment by evanslight** [comment]
This is a disaster. After run this program. I can't run others because of this issue.

**Comment by wmonecke** [comment]
Can someone please disable this package until this is fixed?

**Comment by peacechen** [comment]
PR #84 fixes this and has been published to npm
