### ISSUE TITLE
react-native in dependencies breaks build

### ISSUE THREAD

**Issue by peacechen** [stephy/CalendarPicker#85]
Commit 6c253d9a80a91635f38a8ccc76eb267e599fe1c0 re-introduced react-native to dependencies again.  This results in the error [Update UnableToResolve 'ActivityIndicator'](https://github.com/facebook/react-native/issues/14302) due to a nested copy of react-native inside CalendarPicker.

@stephy : please prioritize removing it and publishing an update to npm as it's breaking any react-native project using this library.

**Comment by peacechen** [comment]
Fixed it in my fork. Since there's an outstanding PR, that commit got lumped in with #84

**Comment by peacechen** [comment]
ping @stephy

**Comment by wmonecke** [comment]
@peacechen Could you please let me know how I can fix this error. I literally am spending hours to fix this.

**Comment by peacechen** [comment]
In your package.json, point to my fork until stephy merges and publishes an update.
```
    "react-native-calendar-picker": "https://github.com/peacechen/CalendarPicker",
```

**Comment by nishiltamboli** [comment]
Thanks @peacechen your fork does look to have solved the issue.

**Comment by stephy** [comment]
@peacechen Hey Thanks for creating a fork and helping everyone out. I have been super busy! Where is the PR you created to solve this issue? I will merge it.

**Comment by peacechen** [comment]
PR #84 Includes the react-native dependency fix.  It includes a number of other fixes & features.  They are relatively minor and have been working well in our app for a while.
