### ISSUE TITLE
Don't install version 5.10.0, it will crash build even you remove it later

### ISSUE THREAD

**Issue by TyrealGray** [stephy/CalendarPicker#88]
I installed version 5.10.0 via npm.
Now even I remove node_module and this CalendarPicker in package.json, my project still not able to rebuild.

The error "Update UnableToResolve 'ActivityIndicator' ..." is showing all the time.

**Comment by harishsn** [comment]
After removing reinstall node modules from yarn

**Comment by TyrealGray** [comment]
I removed project and run `npm start -- --reset-cache` to solve this error.
I am using this https://github.com/wix/react-native-calendars plug-in instead.

**Comment by wmonecke** [comment]
@TyrealGray Could you be more explicit on what you deleted for this to work? I dont want to completely ruin the project.

**Comment by TyrealGray** [comment]
@wmonecke Just run `npm uninstall react-native-calendar-picker`
and then delete you project, run `npm start -- --reset-cache` and re-pull from your repository.

**Comment by wmonecke** [comment]
@TyrealGray Thanks for the response, but sorry if I am being very explicit. Do you mean the iOS and android folders by saying delete your project?

**Comment by TyrealGray** [comment]
@wmonecke I delete the whole react native project folder which is the root folder you run cmd such as `react-native run-ios`

**Comment by peacechen** [comment]
See #85 
Solution is to use my fork until the PR is merged.
