### ISSUE TITLE
Please don't install!!! It could be a disaster!!!! 这个组件有毒！有毒！有毒！

### ISSUE THREAD

**Issue by evanslight** [stephy/CalendarPicker#89]
I tried many methods.  I can't fix it up! uninstall all package and reinstall 1000 times!
I always get an error: can't find ActivityIndicator. Even for a simple hello world program.

**Comment by TyrealGray** [comment]
issues #88 
Could be helpful to you.

**Comment by peacechen** [comment]
See #85 
Solution is to use my fork until the PR is merged.
