### ISSUE TITLE
add peerDependencies to package.json

### ISSUE THREAD

**Issue by JimmyDaddy** [stephy/CalendarPicker#90]
there are many issues caused by 
```
"react": "~15.4.0",
"react-native": "0.42.3",

``` 
can you move them to 

```
  "peerDependencies": {
    "react-native": ">=0.20.0",
    "react": ">=15.4.0
  },
```
???
@stephy  thank you

**Comment by peacechen** [comment]
See #85 
Solution is to use my fork until the PR is merged.

**Comment by afshinm** [comment]
@peacechen I appreciate your work and it does solve the problem but the correct solution is to use `peerDependency` not to remove them IMO.

**Comment by afshinm** [comment]
I have updated my fork using `peerDependency` and it works now: https://github.com/afshinm/JalaliCalendarPicker/blob/master/package.json

**Comment by JimmyDaddy** [comment]
It seems the author doesn't maintain this package anymore

**Comment by peacechen** [comment]
Version 5.11.0 fixe this and has been published to npm
