### ISSUE TITLE
adding this package broke my project and I do not know how to revert! Help!!

### ISSUE THREAD

**Issue by wmonecke** [stephy/CalendarPicker#91]
Anyone know how to revert the issue after installing this package?

`This warning is caused by a @providesModule declaration with the same name across two different files.`

**Comment by nishiltamboli** [comment]
I think your files might be cached. You can remove the plugin with npm uninstall and also, once you do so, make sure you also fire 2 additional commands - 

1. Delete watchman cache if you are using watchman - watchman watch-del-all
2. Clean npm cache - npm start -- --reset-cache

These 2 should be enough to clean your file cache that the react native packager uses.

**Comment by peacechen** [comment]
See #85 
Solution is to use my fork until the PR is merged.
